### ISSUE TITLE
Small error in `src/index.js`

### ISSUE THREAD

**Issue by samlobel** [lingochamp/OnlineScorer-Web#3]
Line 65 says `if (navigator.mediaDevices.getUserMedia !== 'function') { ... }`

I believe it should be `if (typeof navigator.mediaDevices.getUserMedia !== 'function')`.

I found this using the newest version of Firefox, on Linux. I can submit a pull request at some point for this small change.

**Comment by Y--p--Y** [comment]
Thank you for pointing out this silly typo, I've fixed it in a0312496fb5c6c26b0a4bbd627a84051ef8b5476. Please use version 1.0.4.
