### ISSUE TITLE
Where can developers get `appId` and `secret`?

### ISSUE THREAD

**Issue by EastonLee** [lingochamp/OnlineScorer-Web#5]
I note that two strings are needed when `llsRecorder.init` is invoked, it seems that you allow developers create apps then key and secret are generated, but I didn't find where developers can do these things.
```
    secret: 'xx',
    appId: 'xx'
```

**Comment by Y--p--Y** [comment]
Hi @EastonLee, thanks for your interest in this service. Currently it's not open for public, so please contact our custom service for the appId and secret.
